### ISSUE TITLE
Version 12 does not work on GNOME Shell 42.3

### ISSUE THREAD

**Issue by mortenfc** [koolskateguy89/gnome-shell-extension-spotify-controller#17]
![image](https://user-images.githubusercontent.com/46452097/185745160-5bf7dd4d-ed65-4f3f-905d-46c6efceb102.png)

> gnome-shell --version
GNOME Shell 42.3.

I installed it using gnome-shell-extension-manager

when trying to install with Firefox' addon GNOME Shell integration , version 11.1, it gives error:
![image](https://user-images.githubusercontent.com/46452097/185745316-45c0408c-7366-4ad7-a865-c288b770952c.png)

**Comment by Erik0806** [comment]
I just updated to the newest version and had the same error. Using PopOS by the way

**Comment by Bloopps** [comment]
Same here on Ubuntu 22.04

**Comment by koolskateguy89** [comment]
Sorry I uploaded the wrong files unto EGO, I'll fix this soon

**Comment by koolskateguy89** [comment]
I've fixed it now

**Comment by mortenfc** [comment]
That did not fix.
![image](https://user-images.githubusercontent.com/46452097/185759869-323664cf-12dd-4b14-94a3-51ba9005f0cc.png)

It fails to use the loaded / load the MediaPlayer class from mediaPlayer.js
Copying its contents into extension.js fixes it

**Comment by mortenfc** [comment]
Well, it fixed it in version 12, but in version 13 I get another error after copying:
![image](https://user-images.githubusercontent.com/46452097/185760568-126be058-a7bf-49da-a50c-f9b4a02ad4ac.png)

**Comment by koolskateguy89** [comment]
@mortenfc can you try changing [`mediaPlayer.js:36`](https://github.com/koolskateguy89/gnome-shell-extension-spotify-controller/blob/2d789147c058956458aa0e23df2b7edf9a2f5833/spotify-controller%40koolskateguy89/mediaPlayer.js#L36) to `var MediaPlayer = class MediaPlayer {`
and let me know if it works

It works completely fine on my machine

**Comment by mortenfc** [comment]
@koolskateguy89 yes that fixes the not a constructor error, but I still need to remove the following 7 lines to fix the .toggle undefined error:
https://github.com/koolskateguy89/gnome-shell-extension-spotify-controller/compare/v12...v13#diff-a66e68e9531b7f82b451f334cff842cf5c8fd151f58c9de1f982c2de3237e17a

**Comment by koolskateguy89** [comment]
@mortenfc I see, that is very weird, I don't know why that causes the error.

Is it possible to just remove the first 6 lines and it still works?

**Comment by KowerKoint** [comment]
Same here on Pop!_OS 22.04.

Applying `var MediaPlayer = class MediaPlayer {` change and removing 5 lines in `class ControlBar` works.

**Comment by davibpires** [comment]
I still can't run the extensions since the update to version 12. I'm using Ubuntu 20.04. I can't see any error message.
![image](https://user-images.githubusercontent.com/6054083/185866466-2fc0ebbd-2e83-4408-8001-b3fa3539f0df.png)
